### ISSUE TITLE
duplicate content - trailing slashes

### ISSUE THREAD

**Issue by Chrischii** [picocms/Pico#391] opened 2017-06-27 18:06 UTC
Hello,

it looks like that pico cms has problems with generating "duplicate content" (in the eyes of search engines) because the same content is accessible with and without trailing slashes at the end of the urls. There should be only one version in use (would suggest with trailing slashes) and 301 redirects when someone is trying to access the content via an url without trailing slash. That would be more search engine friendly.

Regards

**Comment by PhrozenByte** [comment] 2017-06-27 18:24
This issue is not caused by Pico, Pico *always* returns the same URL for a page.

Nevertheless, you don't need things like a 301 redirect to fix this, simply add a [canonical link element](https://en.wikipedia.org/wiki/Canonical_link_element) to your theme, e.g.

```twig
{% if current_page %}<link rel="canonical" href="{{ current_page.url }}" />{% endif %}
```

**Comment by Chrischii** [comment] 2017-06-27 18:57
But the content is still accessible through two urls... Canonical tag doesn't change anything of this issue, I want only one url version on the whole website with trailing slashes at the end of urls, and if you try to access one url without trailing slash it must 301 redirect to the right version. Internally all urls should be created with a trailing slash, therefore the redirect is only for users who remove the trailing slash or links from other pages who misses the trailing slash.

**Comment by PhrozenByte** [comment] 2017-06-27 19:15
The "search engines see duplicate content" issue is fixed by the canonical link element. If you want a "cosmetic" fix (i.e. a 301 redirect), use Apache's `mod_rewrite` or similar. Again, this issue isn't caused by Pico.

**Comment by Chrischii** [comment] 2017-06-27 20:53
Pico generates the urls without a trailing slash by standard, right? So the canonical link element contains always urls without a trailing slash (with the exception of the root which always has a trailing slash and the non-slash version is 301 redirected to the slash, it so much mixing there). I don't want both urls with the same content are accessible (crawl management). Therefore I must use redirects to the non trailing slash version, but I want to use urls with trailing slashes...

**Comment by PhrozenByte** [comment] 2017-06-27 21:33
This is expected behavior. Pico is open source, you can extend the `Pico` class and overwrite the necessary methods to change it. Said cosmetic issue can be fixed using Apache's `mod_rewrite`. Pico never used inconsistent URLs.

**Closed by PhrozenByte** 2017-06-27 21:33 UTC
Labels: type: Invalid
