### ISSUE TITLE
syntax error, unexpected T_OBJECT_OPERATOR - pico.php line 141 - php 5.3.10

### ISSUE THREAD

**Issue by LostCore** [picocms/Pico#224] opened 2015-05-14 08:16 UTC
The same installation of Pico works well on a remote server but give me a "syntax error, unexpected T_OBJECT_OPERATOR" on my local environment. Inspecting with xdebug I noted that the error is in pico.php line 141:

$content = (new ParsedownExtra())->text($content);

I've PHP 5.3.10.

**Comment by theshka** [comment] 2015-05-14 11:29
I suspect that it might be the namespace on line 1 of pico.php.
Try replacing `use \Michelf\MarkdownExtra;` with `use \erusev\ParsedownExtra;`

If that doesn't work, try setting the `base_url ` to localhost in the config.php file.

**Comment by theshka** [comment] 2015-05-21 00:52
Fixed in commit: 529e268d5b799b558c6f15b4d587dcfbcea8acfb

**Comment by jcm2226** [comment] 2015-06-22 20:47
I'm getting the same error, but I'm using the newest version.

**Comment by jcm2226** [comment] 2015-06-23 15:33
The problem was resolved after I upgraded to 5.4. Are you sure the line
that calls ParseDownExtra is compatible with 5.3?

**Comment by theshka** [comment] 2015-06-23 15:53
Okay, so the problem is that it is not possible to call a method on an object just created with `new` before PHP 5.4. I haven't actually tested this yet, but something like this should work...
``php
$Parsedown = new ParseDownExtra();
$content = $Parsedown->text($content);
```

**Comment by jcm2226** [comment] 2015-06-23 16:06
Thanks!

**Comment by theshka** [comment] 2015-06-23 23:11
Actually fixed in Commit#e942d40187e3d4f94cd3efccfa13c04c05824348

**Closed by theshka** 2015-06-23 23:11 UTC
Labels: pri: Normal, status: In-Progress, type: Bug
